### PR TITLE
Remove scalastyle test hook

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
I can't get this to work when Chisel 3 is installed as a submodule.

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
I didn't mean to click that button.

**Comment by ducky64** [comment]
So the test style configuration actually matters - it disables checks like magic numbers. That this breaks submodules is a bug that has been around for some time, but we never found a solution.

That all the pull request tests are still passing seems to indicate our checkstyle tests aren't doing much at all. The scalastyle check for tests (if they're being run, and it seems like they aren't) should have gone completely nuts.

**Comment by ducky64** [comment]
Workaround for #41

**Comment by palmer-dabbelt** [comment]
Well, you're welcome to either revert this or find a better way to fix it, but nobody can actually use this stuff with that line in there.

**Comment by aswaterman** [comment]
Palmer's being salty, but he's ultimately right.  Other Scala projects don't require their users have ScalaStyle installed, and they don't expect to have a config located at a hard-coded path, because those constraints are absurd.  What do the other projects do?

**Pull request merged**
