### PR TITLE
[stevo]: shift register enable signal now enables ALL registers in th…

### PR DESCRIPTION
**Pull request by stevobailey**
…e chain.

Previously, the enable signal only worked on the first register. Later ones still shifted every cycle. Now they are all controlled by en.

This also fixes the problem in PR #355, so I'll close that one in favor of this one.

### CODE REVIEW

**Comment by aswaterman** [comment]
shouldn't the enable be pipelined down, rather than simply fanning out to all of the stages?

**Comment by stevobailey** [comment]
But then "disabling" the shift register just causes the value in the first register to shift down, filling all the registers, as is currently the case. When would this be the desired behavior? 

My intended use of the enable signal is to enable or disable the shifting for a cycle.

**Comment by aswaterman** [comment]
I see your point.  I guess what I'm describing is Pipe, not ShiftRegister.

**Comment by davidbiancolin** [comment]
Why not also remove the n == 1 case now that this recurses more regularly?

**Comment by aswaterman** [comment]
Agreed.

**Comment by ccelio** [comment]
This is an unacceptable change to the Chisel API.  In the future please adhere to a deprecation schedule.

**Comment by aswaterman** [comment]
In retrospect, I completely agree, @ccelio.  Sorry about that.

**Pull request merged**
