### PR TITLE
Add a tree reduce function to Vec

### PR DESCRIPTION
**Pull request by da-steve101**
Added a few tree reduce operations.
I find I need this structure reduce more than reduceLeft/reduceRight and i think it makes sense to add it to Vec.

I also see a use case for a single layer reduce. For example, to implement some form of time multiplexing on a vec:

``` scala
val outputVec = inputVec.treeLayerReduce(
                         ( a : T, b : T ) => RegNext(Mux( myCond, a, b )),
                         ( a : T ) => RegNext( a ) )
```

Thoughts?

### CODE REVIEW

**Comment by aswaterman** [comment]
I think the general notion is a good idea, but the single-layer vs. multi-layer distinction isn't consistent with scala reductions.  It's closer to fold, but not exactly the same as that, either.

I'd propose adding fold and reduce, which more closely match their counterparts in the scala collections.  (Also, I'd suggest merely documenting the binary tree nature of the reduction, rather than making it part of the name of the function.)

**Comment by da-steve101** [comment]
Just as I was making the request I was thinking I didn't like the function names.
With scala having reduceLeft and reduceRight, perhaps treeReduce -> reduceTree?
Can't think of a good name for the single layer operation. Perhaps pairItems?

**Comment by aswaterman** [comment]
I'm more inclined toward "reduce" over "reduceTree," but I don't feel that strongly about it.

The single-layer case just isn't consistent with the reduce pattern, though... maybe it should be split into two phases (e.g., map followed by reduce) or handled with fold (where an identity element is explicitly passed).

**Comment by da-steve101** [comment]
Changed to reduce. I think pair is a bit better for the single layer.
I don't think it should be split up. It would have an intermediate state which would be messy to handle
```scala
Vec( UInt(1), UInt(2), UInt(3), UInt(4), UInt(5) ).grouped(2) => {
  IndexedSeq( ( UInt(1), UInt2 ), ( UInt(3), UInt(4) ), ( UInt(5) ) )
}
```

**Comment by da-steve101** [comment]
I removed the single layer function. I think any name will be ambiguous and can easily be constructed in a clearer way using grouped(2).map( ... )

**Comment by aswaterman** [comment]
I agree.

However, I still think it's quite confusing that reduce doesn't mirror that of the scala collections.  Its only argument is a function that combines (T, T) => T.  In the case that the input has just one element, it simply returns that element.  If you want to do something to each element prior to combining them, you can map over them first.

**Comment by da-steve101** [comment]
In the case of a fully pipelined adder tree, I don't see how you could map the adding of 10 numbers as the second stage would need a register not there initially.
I think a default value of an identity function is better but unfortunately its not supported :/
See [SI-5920](https://issues.scala-lang.org/browse/SI-5920)
Replacing the scala reduce is the wrong approach in my opinion as the sequential behaviour could be expected. I think along the lines of reduceLeft and reduceRight, reduceTree is an appropriate name.
I have defined two macros for reduceTree, with and without the second argument. Its a little ugly, but I don't see a better way to do it.

**Comment by aswaterman** [comment]
I actually favor having two implementations over the default argument in this case.

I'd like @sdtwigg to weigh in, but I'm in favor of merging.

**Comment by jackkoenig** [comment]
ok to test

**Comment by jackkoenig** [comment]
Replaced by #485

**Pull request closed without merging**
