### PR TITLE
Digit record field

### PR DESCRIPTION
**Pull request by jackkoenig**
This incorporates the fixes from @terpstra and @mwachs5. I merged their commits because they kinda went together while I think the other 2 are separate. In particular, @ducky64, can you look at the first commit which changes and uses NamedModuleTester?

### CODE REVIEW

**Comment by ducky64** [comment]
Only comment is that expectParentName sounds like a very roundabout way of getting the name of a Module, is there no way to specify expectModuleName?

**Comment by jackkoenig** [comment]
Actually I think I can use just `Module.name`: https://github.com/ucb-bar/chisel3/blob/563f348ca3e4a984ad23caba9e980dab8fa808bb/chiselFrontend/src/main/scala/chisel3/core/Module.scala#L148

For some reason I thought final naming occurred in emission so this wouldn't be possible, but I think that was either just for blackboxes or was removed when we added `defname` to Firrtl `extmodules`

**Comment by jackkoenig** [comment]
Done, better @ducky64? Using the parent name of the io was a bit wonky, I figured it was fine since it was just a test but yeah, this is much better.

**Comment by jackkoenig** [comment]
I always hated how it was done, glad you figured out a better way in the NamingAnnotationTests.

**Comment by jackkoenig** [comment]
I'm going to rebase to maintain some of the separate commits

**Pull request merged**
