### PR TITLE
Add whenever method to TblSpec forall to weed out invalid test values.

### PR DESCRIPTION
**Pull request by ucbjrl**
This branch can be deleted when merged.

### CODE REVIEW

**Comment by ucbjrl** [comment]
retest this please

**Comment by ucbjrl** [comment]
Or perhaps this approach is better:
  [Add support for not shrinking values in GeneratorDrivenPropertyChecks #584](https://github.com/scalatest/scalatest/issues/584)

**Comment by aswaterman** [comment]
I think this is fine, since the whenever condition is nearly always met.  I'd favor a different approach if it were filtering out a large fraction of potential test vectors.

**Comment by aswaterman** [comment]
Merged via 19046381ae319915c4e8fff7b108e6b5dd100509

**Pull request closed without merging**
