### PR TITLE
Add Assert Data

### PR DESCRIPTION
**Pull request by sdtwigg**
Allow user to insert Bits into their assert message.
printf allows the use of format specifiers for inserting data from Bits
at hardware simulation time into the message. This just extends assert
to allow the same.

### CODE REVIEW

**Comment by aswaterman** [comment]
what's up with the first 4 commits being in this PR?

**Comment by sdtwigg** [comment]
I'm actually unsure given those were already merged....

**Comment by sdtwigg** [comment]
Weird commits resolved. Had to trick github/git into properly believing the old commits were merged.

**Comment by aswaterman** [comment]
I support merging this but can you make it apply cleanly against master?

**Comment by ucbjrl** [comment]
Closed by #318 , #319

**Pull request closed without merging**
