### PR TITLE
Make fromBits work with types other than UInt

### PR DESCRIPTION
**Pull request by grebe**
My attempt to address #421 

Data now has no default implementation for do_fromBits. The previous default implementation is moved to Aggregate, and each flavor of Bits has it's own implementation too.

I'm not sure if fromBits should be legal for a clock, or if it should just throw and exception. Right now it just makes a clock wire and uses the := operator.

### CODE REVIEW

**Comment by ducky64** [comment]
Implementation looks sane, but (sorry to turn everything into an API discussion) I think this raises the question whether fromBits is a good API to have. We already have the functionally-equivalent Bits.asSInt | asUInt (in fact, your implementation just delegates to those), and it makes no sense to try to make a Clock from Bits (other than Bool.asClock). Realistically, I think the only compelling reason for fromBits is Aggregate types (where you want chisel to handle packing and unpacking consistently), so it might make more sense to have fromBits (and maybe flatten?) as an Aggregate operation?

**Comment by sdtwigg** [comment]
Our approach was the following:
1. asUInt or from[blah] on a Clock is a runtime-exception (iirc FIRRTL doesn't support this at all anyway)
2. Instead of fromBits, Data has an "asTypeOf[T <: Data](model: T): T" since most commonly people were using fromBits to perform a cast and this made all casts look like as[blah]. This also made asTypeOf invert itself. (There are potentially some odd cases when unknown-width SInts are involved; however, it was generally advised to use only known width things under threat of emitting errors later.)
3. asTypeOf uses connectFromUInt(target: UInt) for each element, which basically acts like your proposed fromBits (but without having to worry about which Bits it is). connectFromUInt also doesn't create any wires.

**Comment by grebe** [comment]
@ducky64 I agree with you that fromBits is probably not a good API. In addition to the points you bring up, I don't like how it uses `this.type`. I think the approach @sdtwigg outlined looks like a much better API and I would vote for moving to that. Was this part of a previous PR that didn't make it in for some reason?

I still think it is probably worth merging something similar to this PR. Making an API change requires debate that will be further slowed by the holidays and the retreat, and this fixes a bug that is causing problems for us now (specifically with unpacking and packing for our axi4s ports in craft).

**Comment by sdtwigg** [comment]
Yes, you should definitely merge this as a bugfix since the other proposals would likely end up using it anyway.

I think I had done this API change in late July. It was after my initial large pull request during that period when there was no interest in my pull request (but also long enough ago that I had actually thought this was part of that PR). As an amusing anecdote, I think it pushing the exact bugfix you are doing now (SInt just didn't work) a few weeks earlier which triggered the desire for an API re-examination.

**Comment by ducky64** [comment]
For this PR itself, I think it would be good to have a test that checks that when you do (some UInt).fromBits, the resulting UInt is of the same width. At least truncation behavior can be checked using the data value, while you might need DataMirror to check width increases.

@sdtwigg can you open an issue proposing a fromBits API change? I think your API is less confusing and more consistent with the other conversions. It should also be possible to keep Bundle.fromBits in the compatibility layer.

**Comment by ducky64** [comment]
@grebe if you add the width tests (larger UInt will be truncated to fit within a smaller UInt it's being converted to; smaller UInt will be width expanded when converted to a larger UInt - this can be checked using DataMirror), I'll approve this.

**Comment by grebe** [comment]
Not sure what DataMirror is for or if I used it correctly, but here is my attempt. Does this look OK?

**Comment by grebe** [comment]
Also, I believe #391 is not addressed by this and is still needed for FixedPoint to work

**Comment by grebe** [comment]
#391 got merged and broke something, so I just pushed a fix. I also added a test case.

**Pull request merged**
