### PR TITLE
Add shift register with reset

### PR DESCRIPTION
**Pull request by stevobailey**
Open to discussion. It resets all registers in the shift to the same value. This is sufficient for my needs.

### CODE REVIEW

**Comment by edwardcwang** [comment]
1) Is there a corresponding test in `src/test/scala/chiselTests/Reg.scala`?

2) Seems reasonable to squash the second commit into the first since it modifies the previous one.

**Comment by ducky64** [comment]
Might be worth waiting until #438 is resolved, so we can keep semantics consistent. That this overloads a function with a slightly-different-but-not-that-much-different type signature (with reset vs. without reset) kind of "smells" off.

Squash protip: there's a "squash and merge" button on GitHub. (see end of https://github.com/blog/2141-squash-your-commits)

**Comment by stevobailey** [comment]
1. No, but I didn't see a shift register test there either...there's a ShiftRegisterTester in Vec.scala (but it tests a Vec + Counter, not a ShiftRegister).
2. As Richard says, squash and merge can be done once approved.
3. Okay, we'll wait for #438

**Comment by grebe** [comment]
I wouldn't advocate waiting for #438 - that issue has been around forever in one form or another. ShiftRegister already exists- whatever happens with the issue will impact it regardless. This new apply just parallels the two already existing implementations of RegEnable.

**Comment by ducky64** [comment]
I'm pushing for a resolution for #438 within a week and implementation (if necessary) to follow shortly after.

**Comment by stevobailey** [comment]
Bump. Richard, it doesn't look like #455 changes the API, so this should still be valid. Can we merge?

**Comment by ducky64** [comment]
This doesn't break anything, but it does an API item which we would have to maintain continued support for. I'd like broader agreement on this before merging.
@jackkoenig @azidar

**Comment by ducky64** [comment]
This doesn't break any existing APIs, but it does add a new API item, which I think should have wider consensus. @azidar @jackkoenig ?

**Comment by azidar** [comment]
I'm fine with this.

**Comment by grebe** [comment]
Does the approver do the merge or the pull-requester?

**Comment by ducky64** [comment]
I would prefer the requester does the merge (in case someone has a last-minute-fix moment), though it's kind of been a free-for-all.

**Comment by ucbjrl** [comment]
I believe we encourage the requester to do the merge (assuming they have
push access), so they can deal with any conflicts that arise post approval.

**Comment by stevobailey** [comment]
Okay I don't have push access, so I can't merge.

**Pull request merged**
