### PR TITLE
Emit no width instead of <?> for unknown width UInt and SInt literals…

### PR DESCRIPTION
**Pull request by jackkoenig**
… and types

Fix for #105

### CODE REVIEW

**Comment by jackkoenig** [comment]
Investigating failures

**Comment by jackkoenig** [comment]
So I think there are a couple of firrtl bugs, but I think the vast majority of the tests failed here are because firrtl is not in the path for the jenkins runs. @ucbjrl can you look into this?

**Comment by ucbjrl** [comment]
retest this please

**Comment by ucbjrl** [comment]
retest this please

**Comment by ucbjrl** [comment]
retest this please

**Comment by ucbjrl** [comment]
retest this please

**Comment by ucbjrl** [comment]
retest this please

**Comment by ucbjrl** [comment]
retest this please

**Comment by ucbjrl** [comment]
retest this please

**Comment by ucbjrl** [comment]
You were correct Jack. Unfortunately, supporting multiple Jenkins jobs in flight with potentially different versions of chisel3 and firrtl required more tweaking than it should.
This should be working now.

**Comment by jackkoenig** [comment]
retest this please

**Pull request merged**
