### PR TITLE
Add pointer to Chisel3 compatibility on Chisel2 README.

### PR DESCRIPTION
**Pull request by ucbjrl**
This branch may be deleted when merged.

### CODE REVIEW

**Comment by ducky64** [comment]
Did you mean "refer to *the* Chisel2 README"?

Also, you can link to a specific subsection of the Chisel2 README:
https://github.com/ucb-bar/chisel#chisel3

**Comment by ucbjrl** [comment]
Yes to both. Thanks Richard. I'll update the pr.

**Comment by ducky64** [comment]
Sorry, one more nit: the two-space indent on the new lines indicates that it's part of a list element, so it ends up in the sequential memories section. I think it makes more sense to eliminate the indent.

**Comment by ucbjrl** [comment]
Good catch.

**Comment by ducky64** [comment]
lgtm

**Pull request merged**
