### PR TITLE
doesn't lose old firrtl options annotations + transforms

### PR DESCRIPTION
**Pull request by shunshou**
Problem: For Driver.execute, when you tried passing transforms/annotations via FirrtlOptions, they'd get overwritten before they ever got to Firrtl. Now I'm just appending the new stuff to what was already there...

Execution options are really hairy and poorly maintained across the various levels of Chisel hierarchy...

### CODE REVIEW

**Comment by shunshou** [comment]
@chick mind if I merge?

**Comment by colinschmidt** [comment]
I believe the current practice in chisel+firrtl is that once you get approval you are free to merge.

**Comment by shunshou** [comment]
Ok then I'll merge. :P

**Comment by jackkoenig** [comment]
Make sure to squash and merge though (to ensure the merge master commit doesn't make it in too)

**Pull request merged**
