### PR TITLE
Print a better message on constant width failures

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
I'm getting this error and the message is awful.

### CODE REVIEW

**Comment by aswaterman** [comment]
Your patch just adds an esoteric diagnostic message.

**Comment by aswaterman** [comment]
How about something like "literal X can only be represented in at least Y bits; Z doesn't suffice"

**Comment by palmer-dabbelt** [comment]
Sorry, that was garbage.  This should be less so.

**Comment by aswaterman** [comment]
lgtm

**Pull request merged**
