### PR TITLE
Make "def width" a private API; expose isWidthKnown instead

### LINKED ISSUE #256: Chisel does not like parameters in modules that are called width
This has been cropping up for a while now. Chisel gives really inscrutable error messages if you ever name a parameter to a module or bundle "width". It's easy to work around, but it does cause a lot of confusion when you encounter it. If you try to instantiate a module in Chisel that is declared as follows ...

    class AdjustableWidth(width: Int) extends Module {
      val io = new Bundle {
        val out = UInt(OUTPUT, width=width)
      }

      io.out := UInt(1)
    }

You get the error message

    java.lang.reflect.InvocationTargetException
    Caused by: java.lang.UnsupportedOperationException: empty.reduceLeft
        at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:178)
        at scala.collection.mutable.ArrayBuffer.scala$collection$IndexedSeqOptimized$$super$reduceLeft(ArrayBuffer.scala:48)
        at scala.collection.IndexedSeqOptimized$class.reduceLeft(IndexedSeqOptimized.scala:74)
        at scala.collection.mutable.ArrayBuffer.reduceLeft(ArrayBuffer.scala:48)
        at scala.collection.TraversableOnce$class.reduce(TraversableOnce.scala:206)
        at scala.collection.AbstractTraversable.reduce(Traversable.scala:104)
        at chisel3.core.Aggregate.width(Aggregate.scala:19)

However, just changing it by renaming the parameter makes it work just fine.

    class AdjustableWidth(w: Int) extends Module {
      val io = new Bundle {
        val out = UInt(OUTPUT, width=w)
      }

      io.out := UInt(1)
    }

Full example at https://github.com/zhemao/chiselbugs/blob/master/src/main/scala/WidthParameter.scala

### PR DESCRIPTION
**Pull request by aswaterman**
Resolves #256.

Since width was used to determine whether getWidth would succeed, I added

    def isWidthKnown: Boolean

but another option would be to expose something like

    def widthOption: Option[Int]

...thoughts?

### CODE REVIEW

**Comment by ucbjrl** [comment]
I vote for the first - isWidthKnown. It seems like the scenarios under which one would use this, would involve triggering additional code (optimizations) having nothing to do with the actual value itself. The second case (Option[Int]) seems more geared to providing a "default" value in the case the value is None. I suspect the latter usage will rarely arise in practice.

**Comment by aswaterman** [comment]
For the second case, I was thinking that instead of writing code like

    if (x.isWidthKnown)
      doSomething(x.getWidth)
    else
      doSomethingElse

you'd write something like

    x.widthOption match {
      case Some(w) => doSomething(w)
      case None => doSomethingElse
    }

**Comment by aswaterman** [comment]
so I think it's just a matter of taste

**Comment by ucbjrl** [comment]
Hmmm. Or:

    x.widthOption match {
      case Some(32) => doSomethingWithTheOneTrueWidth(32)
      case Some(w) => doSomething(w)
      case None => doSomethingElse
    }

**Comment by jackkoenig** [comment]
Porque no los dos?

I think isWidthKnown has a lot of utility but returning Option[Int] allows people to do more functional and "Scala-y" things like Andrew's example.

**Comment by aswaterman** [comment]
good point

**Pull request merged**
