### PR TITLE
Classic tester cleanup

### PR DESCRIPTION
**Pull request by jackkoenig**
Cleanup of #179 

I think the naming of buildModule vs build and elaborateModule vs elaborate is a little weird, any suggestions?

### CODE REVIEW

**Comment by sdtwigg** [comment]
Agreed, also:
For build vs buildModule, they both do nearly the same thing. build should call buildModule at least?

Where is buildModule and elaborateModule used? (could hint at better naming)
The referenced PR just adds them and only says the functionality is needed but not 'Why?'

**Comment by jackkoenig** [comment]
I agree.

I definitely think build should call buildModule, but how does that work dynamicContextVar { ... scope stuff? Perhaps they both call a 3rd common module that does the dynamicContext stuff?

I believe buildModule and elaborateModule are used in the classic tester, @dt27182 is going to add comments to clarify this I think, but better name ideas would be appreciated.

**Comment by dt27182** [comment]
buildModule is used by the Chisel3 implementation of the software tester so that It can get an instance of the Chisel Module and inspect its io bundle. I have just added the comments to this branch.

I'm not familiar with how the dynamic context stuff works, but adding another module for this seems too complicated.

**Comment by sdtwigg** [comment]
Okay, I looked into it. DynamicVariable and DynamicContext are scala util constructs for dealing with keeping data local to a thread.

Why are these being used in Chisel3 at all? There are zero comments justifying their use. This is annoying because their use complicates everything around them.

**Comment by jackkoenig** [comment]
@aswaterman can elaborate, but I believe they were used because it made it much easier to write Chisel 3 by using global state via DynamicVariable for thread safety

**Comment by aswaterman** [comment]
It's actually @hcook who made the design decision, so he can elaborate, but basically it maintains the global state and module stack in a thread-safe manner.

**Comment by sdtwigg** [comment]
I assumed it was for thread safety (given the docs for it draw parallels to
Java. ThreadLocal). The issue is that it is kinda tricky to untangle what
is actually stored in there without comments. :/

**Comment by jackkoenig** [comment]
As for this PR, I'm not sure I see how these two functions can share code at the moment, so that might have to be future work (if we ever replace the DynamicVariable with perhaps some context that gets passed around?)

I still would like better names for the functions though

**Comment by jackkoenig** [comment]
I've pushed an alternative implementation that changes Builder.build to return both the elaborated Circuit and the original Chisel Module that has now been constructed.

I still am a bit iffy about this approach since all the classic tester really needs is the ability to use scala dot notation to *refer* to the members of the Module. I believe this may better be accomplished by generating a case class from the FIRRTL emitted by the Module. My guess is this can only be done with macros, but this blog (http://blog.echo.sh/2013/11/04/exploring-scala-macros-map-to-case-class-conversion.html) has a similar type of case. 

In the meantime, the classic tester *could* use a lazy val to skirt around until we can figure out the macro solution.

Thoughts?

**Comment by jackkoenig** [comment]
On the other hand, using a macro for this seems kind of like using a sledgehammer to crack a nut.

In #137, @chick mentioned that providing a default dynamic context allows you to just do: `val mod = new ChiselModule`. I suspect there is some danger here of users trying to do this to build circuits which isn't right, but maybe not. It definitely seems like a more appropriate way to deal with the problem this PR is trying to address.

**Comment by ucbjrl** [comment]
Is this still relevant? @jackkoenig could you resolve this if so?

**Comment by jackkoenig** [comment]
I don't think so

**Pull request closed without merging**
